Working with data

We ran a special promotion in July aimed at improving retention. New users were sent a letter with a coupon. Did the promotion work?

https://drive.google.com/file/d/1TPu_Yu--g1Lne6ONpJyEhhQ3EzJkM0qt/view?usp=sharing

In [27]:
# import file

In [28]:
! gdown --id 1TPu_Yu--g1Lne6ONpJyEhhQ3EzJkM0qt

/usr/local/lib/python3.11/dist-packages/gdown/__main__.py:140: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1TPu_Yu--g1Lne6ONpJyEhhQ3EzJkM0qt
To: /content/analyst_test_transactions_db.csv
100% 3.07M/3.07M [00:00<00:00, 195MB/s]

In [29]:
import pandas as pd

In [30]:
import numpy as np

In [31]:
df = pd.read_csv('/content/analyst_test_transactions_db.csv')

In [32]:
df.head()

   user_id  order_id    reg_date transaction_date  revenue
0    57562   94545.0  2013-12-22       2015-07-16     1088
1    40047   81824.0  2013-11-24       2015-01-19     1027
2    48153  144851.0  2015-07-03       2015-10-29      601
3    54591  116111.0  2013-07-12       2015-04-30      881
4    39789  134943.0  2013-05-25       2015-07-21      984

In [33]:
len(df)

76857

In [34]:
df.dtypes

user_id               int64
order_id            float64
reg_date             object
transaction_date     object
revenue               int64
dtype: object

In [35]:
# convert date (reg_date, transaction_date) to required data type
df['reg_date'] = pd.to_datetime(df['reg_date'], format='%Y-%m-%d')
df['transaction_date'] = pd.to_datetime(df['transaction_date'], format='%Y-%m-%d')

In [37]:
# first day of the month
df['reg_month'] = df['reg_date'].to_numpy().astype('datetime64[M]')

In [38]:
df.head()

   user_id  order_id   reg_date transaction_date  revenue  reg_month
0    57562   94545.0 2013-12-22       2015-07-16     1088 2013-12-01
1    40047   81824.0 2013-11-24       2015-01-19     1027 2013-11-01
2    48153  144851.0 2015-07-03       2015-10-29      601 2015-07-01
3    54591  116111.0 2013-07-12       2015-04-30      881 2013-07-01
4    39789  134943.0 2013-05-25       2015-07-21      984 2013-05-01

In [39]:
# group users by the month

In [40]:
df.groupby('reg_month')['user_id'].agg(['count', 'nunique'])

            count  nunique
reg_month
1900-01-01     53       53
2012-02-01      9        9
2012-03-01    362      361
2012-04-01    370      370
2012-05-01    301      301
2012-06-01    445      443
2012-07-01    370      369
2012-08-01    271      269
2012-09-01    356      355
2012-10-01    367      367
2012-11-01    272      272
2012-12-01    538      535
2013-01-01    418      418
2013-02-01    654      653
2013-03-01   1161     1158
2013-04-01    844      837
2013-05-01   1081     1076
2013-06-01    941      931
2013-07-01   1103     1097
2013-08-01   1201     1191
2013-09-01   1004      994
2013-10-01    822      815
2013-11-01   1136     1124
2013-12-01   1584     1566
2014-01-01   1424     1406
2014-02-01   1339     1329
2014-03-01   1520     1505
2014-04-01   1625     1602
2014-05-01   1514     1493
2014-06-01   1911     1892
2014-07-01   1811     1793
2014-08-01   2395     2348
2014-09-01   2593     2544
2014-10-01   2967     2909
2014-11-01   2946     2883
2014-12-01   4713     4556
2015-01-01   4195     4083
2015-02-01   3652     3570
2015-03-01   3646     3557
2015-04-01   3411     3327
2015-05-01   2706     2652
2015-06-01   3568     3477
2015-07-01   4376     4236
2015-08-01   3319     3230
2015-09-01   2422     2398
2015-10-01   2239     2209
2015-11-01    902      898